CREATE TABLE app_schema_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    role VARCHAR(20) DEFAULT 'MEMBER' NOT NULL,
    account_status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    must_change_password BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ux_members_email ON members (email);
CREATE UNIQUE INDEX ux_members_username ON members (username);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(5000) NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'TWD' NOT NULL,
    stock INT DEFAULT 0 NOT NULL,
    category VARCHAR(100) NOT NULL,
    status VARCHAR(20) DEFAULT 'PUBLISHED' NOT NULL,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES members(member_id),
    CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0),
    CONSTRAINT ck_products_currency_twd CHECK (currency = 'TWD'),
    CONSTRAINT ck_products_status CHECK (status IN ('PUBLISHED', 'UNPUBLISHED'))
);

CREATE TABLE product_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    storage_key VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL,
    sort_order INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT uq_product_images_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_product_images_size_positive CHECK (file_size > 0),
    CONSTRAINT ck_product_images_type CHECK (media_type IN ('image/jpeg', 'image/png', 'image/webp'))
);

CREATE INDEX ix_products_public_listing ON products (status, deleted_at, created_at);
CREATE INDEX ix_products_seller ON products (seller_id, deleted_at, created_at);
CREATE INDEX ix_product_images_product ON product_images (product_id, sort_order, image_id);

CREATE TABLE carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    seller_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_carts_member UNIQUE (member_id),
    CONSTRAINT fk_carts_member FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT fk_carts_seller FOREIGN KEY (seller_id) REFERENCES members(member_id)
);

CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_cart_items_product UNIQUE (cart_id, product_id),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts(cart_id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT ck_cart_items_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX ix_cart_items_cart ON cart_items (cart_id, product_id);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    subtotal_amount DECIMAL(19,2) NOT NULL,
    shipping_fee DECIMAL(19,2) NOT NULL,
    total_amount DECIMAL(19,2) NOT NULL,
    shipping_method VARCHAR(30) NOT NULL,
    recipient_name VARCHAR(100) NOT NULL,
    recipient_phone VARCHAR(30) NOT NULL,
    store_name VARCHAR(100),
    store_code VARCHAR(30),
    delivery_address VARCHAR(300),
    status VARCHAR(30) DEFAULT 'PAID' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES members(member_id),
    CONSTRAINT fk_orders_seller FOREIGN KEY (seller_id) REFERENCES members(member_id),
    CONSTRAINT ck_orders_amounts_non_negative CHECK (subtotal_amount >= 0 AND shipping_fee >= 0 AND total_amount >= 0),
    CONSTRAINT ck_orders_shipping_method CHECK (shipping_method IN ('CONVENIENCE_STORE', 'HOME_DELIVERY')),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'PENDING_SHIPMENT', 'SHIPPED', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    unit_price DECIMAL(19,2) NOT NULL,
    quantity INT NOT NULL,
    line_amount DECIMAL(19,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_order_items_seller FOREIGN KEY (seller_id) REFERENCES members(member_id),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_amounts_non_negative CHECK (unit_price >= 0 AND line_amount >= 0)
);

CREATE TABLE payment_attempts (
    payment_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    member_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    mock_account_name VARCHAR(100) NOT NULL,
    mock_account_number VARCHAR(100) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_attempts_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT fk_payment_attempts_member FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT ck_payment_attempts_status CHECK (payment_status IN ('SUCCESS', 'FAILED'))
);

CREATE TABLE checkout_requests (
    checkout_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    result_status VARCHAR(20) NOT NULL,
    order_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_checkout_requests_member_key UNIQUE (member_id, idempotency_key),
    CONSTRAINT fk_checkout_requests_member FOREIGN KEY (member_id) REFERENCES members(member_id),
    CONSTRAINT fk_checkout_requests_order FOREIGN KEY (order_id) REFERENCES orders(order_id),
    CONSTRAINT ck_checkout_requests_status CHECK (result_status IN ('SUCCESS', 'FAILED'))
);

CREATE INDEX ix_orders_buyer ON orders (buyer_id, created_at, order_id);
CREATE INDEX ix_orders_seller ON orders (seller_id, created_at, order_id);
CREATE INDEX ix_order_items_order ON order_items (order_id, order_item_id);
CREATE INDEX ix_payment_attempts_member ON payment_attempts (member_id, created_at);

CREATE TABLE order_status_history (
    status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_status_history_member FOREIGN KEY (changed_by) REFERENCES members(member_id),
    CONSTRAINT ck_order_status_history_status CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'PENDING_SHIPMENT', 'SHIPPED', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE order_shipments (
    order_id BIGINT PRIMARY KEY,
    tracking_number VARCHAR(100) NOT NULL UNIQUE,
    shipped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_shipments_order FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE
);

CREATE INDEX ix_order_status_history_order ON order_status_history (order_id, changed_at, status_history_id);
