CREATE TABLE app_schema_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schema_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    role VARCHAR(20) DEFAULT 'MEMBER' NOT NULL,
    account_status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    must_change_password BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX ux_members_email ON members (email);
CREATE UNIQUE INDEX ux_members_username ON members (username);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(5000) NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'TWD' NOT NULL,
    stock INT DEFAULT 0 NOT NULL,
    category VARCHAR(100) NOT NULL,
    status VARCHAR(20) DEFAULT 'PUBLISHED' NOT NULL,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES members(member_id),
    CONSTRAINT ck_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0),
    CONSTRAINT ck_products_currency_twd CHECK (currency = 'TWD'),
    CONSTRAINT ck_products_status CHECK (status IN ('PUBLISHED', 'UNPUBLISHED'))
);

CREATE TABLE product_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    storage_key VARCHAR(100) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    file_size BIGINT NOT NULL,
    sort_order INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT uq_product_images_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_product_images_size_positive CHECK (file_size > 0),
    CONSTRAINT ck_product_images_type CHECK (media_type IN ('image/jpeg', 'image/png', 'image/webp'))
);

CREATE INDEX ix_products_public_listing ON products (status, deleted_at, created_at);
CREATE INDEX ix_products_seller ON products (seller_id, deleted_at, created_at);
CREATE INDEX ix_product_images_product ON product_images (product_id, sort_order, image_id);
